# -*- coding: utf-8 -*-
"""UTS Deep Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3R7CqUQFt7qFZCzp0EJvzPRVmn0xaSE
"""

!pip install ultralytics

from ultralytics import YOLO
# Create a new YOLO model from scratch
model = YOLO('yolov8n.yaml')

# Load a pretrained YOLO model (recommended for training)
model = YOLO('yolov8n.pt')

# Train the model using the 'coco128.yaml' dataset for 3 epochs
results = model.train(data='coco128.yaml', epochs=100)

# Evaluate the model's performance on the validation set
results = model.val()

from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Run inference on 'bus.jpg' with arguments
model.predict('basebal.jpg', save=True, imgsz=320, conf=0.5)

# Export the model to ONNX format
success = model.export(format='onnx')

import os
from IPython.display import display, Image
from IPython import display
display.clear_output()

Image(filename=f'/content/runs/detect/predict22/basebal.jpg',width=600)

import locale
locale.getpreferredencoding = lambda: "UTF-8"

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="CzeGX7aw0a8twHgKp5yM")
project = rf.workspace("cu-jy9ge").project("caulong")
dataset = project.version(3).download("yolov8")

# Train the model using the 'coco128.yaml' dataset for 100 epochs
results = model.train(data='/content/caulong-3/data.yaml', epochs=10)

# Perform object detection on an image using the model
results = model('/content/badminton.jpg')

from ultralytics import YOLO

# Run inference on 'bus.jpg' with arguments
model.predict('badminton.jpg', save=True, imgsz=320, conf=0.5)

import os
from IPython.display import display, Image
from IPython import display
display.clear_output()

Image(filename=f'/content/runs/detect/train33352/badminton.jpg', width=600)

